#!/bin/bash
#Installation

##Tested on:

#- Raspbian (RaspberryPi - think of those possibilities)

#```

# All of these commands are run from the base folder (SunFounder_Smart_Video_Car_Kit_V2.0_for_Raspberry_Pi), wherever you clone it to

if [ "$(whoami)" != "root" ] ; then
    echo "You must run setup.sh as root."
    exit
fi

sudo apt-get update
#sudo apt-get upgrade -y

###################################
# install python-pip django i2c-tools python-smbus runtime #
###################################
    echo "\n    Installing  python-pip and django \n"
    if sudo apt-get install python-pip ; then
        echo "Successfully installed python-pip \n "
    else
        echo "Failed to installed python-pip"
        exit
    fi
    if sudo pip install django ; then
        echo "Successfully installed django runtime \n"
    else
        echo "Failed to installed django"
        exit
    fi

    echo "\n    Installinging i2c-tools and python-smbus \n"
    if sudo apt-get install i2c-tools python-smbus -y; then
        echo "Successfully installed i2c-tools python-smbus \n"
    else
        echo "Failed to installed i2c-tools python-smbus"
        exit
    fi

###################################
# Copy MJPG-Streamer to an Alternate Location #
###################################
#
echo "Copy MJPG-Streamer to an Alternate Location "
sudo cp mjpg-streamer/mjpg_streamer /usr/local/bin
sudo cp mjpg-streamer/output_http.so mjpg-streamer/input_file.so mjpg-streamer/input_uvc.so /usr/local/lib/
sudo cp -R mjpg-streamer/www /usr/local/www
echo "complete\n"

###################################
# Export Paths #
###################################
#
echo "Export paths"
echo export LD_LIBRARY_PATH=/usr/local/lib/ >> ~/.bashrc
echo export LD_LIBRARY_PATH=/usr/local/lib/ >> ~/.profile
source ~/.bashrc
echo "complete\n"

###################################
# Enable I2C1 #
###################################
# Add lines to /boot/config.txt
echo "\n    Enalbe I2C \n"
egrep -v "^#|^$" /boot/config.txt > config.txt.bak  # pick up all uncomment configrations
if grep -q 'dtparam=i2c_arm=on' config.txt.bak; then  # whether i2c_arm in uncomment configrations or not
    echo 'Seem i2c_arm parameter already set, skip this step'
else
    echo 'dtparam=i2c_arm=on' >> /boot/config.txt
fi
rm config.txt.bak   
echo "\n complete, now reboot to take effect\n"
sudo reboot
