#!/bin/bash

### BEGIN INIT INFO
# Provides:          SunFounder PiCar-V snap
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: snap!4.0 initscript
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$1" in
    start)
        echo "Starting PiCar-V Snap"
        cd /home/pi/SunFounder_PiCar-V/PiCar-V_Snap
        sudo python /home/pi/SunFounder_PiCar-V/PiCar-V_Snap/picar-v_snap.py &
        ;;
    stop)
        echo "PiCar-V Snap Stop"
        # kill all picar-v_snap.py
        kill $(ps aux | grep -m 1 '/home/pi/SunFounder_PiCar-V/PiCar-V_Snap/picar-v_snap.py' | awk '{ print $2 }')
        ;;
    *)
        echo "Usage: service snap start|stop"
        exit 1
        ;;
esac
exit 0