#!/bin/bash

# This script will help you build a system service named snap to run picar_v_snap.py
# Use as: sudo service snap start
#     or: sudo service snap stop
# It also ask you if run the service on system start up.

# Record the dirname whitch snap in and cd to the dir
snap_dir=$(cd `dirname $0`;pwd)
cd $snap_dir
echo "snap_dir: "$snap_dir

function if_continue(){
    while :; do
        echo  -e "(yes/no) \c"
        read input_item
        if [ $input_item = "yes" ]; then
            break
        elif [ $input_item = "no" ]; then
            return 0
        else
            echo -e "Input error, please try again."
        fi
    done
    return 1
}

#echo "ln snap script to /etc/init.d and reload system service "
sudo cp $snap_dir/snap /etc/init.d/snap
sudo systemctl daemon-reload

# Run the service on system start up or not
echo "Run the snap on start up? "
if_continue
if [ $? = 1 ]; then
    sudo update-rc.d snap defaults
else
    sudo update-rc.d snap disable
fi
exit