#!/bin/sh
#**********************************************************************
#* Filename    : start
#* Description : a simple bash script to run the django server
#* Author      : Cavon
#* Brand       : SunFounder
#* E-mail      : service@sunfounder.com
#* Website     : www.sunfounder.com
#* Update      : Cavon    2016-09-13    New release
#**********************************************************************

# Run server listen to any IP address and port 8000
python manage.py runserver 0.0.0.0:8000
